image: gcc:6.1

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -y install cmake
          - apt-get -y install libx11-dev mesa-common-dev libglu1-mesa-dev libxrender-dev libxfixes-dev libglew-dev
          - mkdir build
          - cd build
          - cmake ..
          - make